# Tox (https://tox.wiki/) is a tool for running tests in multiple
# virtualenvs. This configuration file will run the test suite on all
# supported python versions. To use it, run "tox" from this directory.
#
# For a specific environment, run:
#     "tox -e <env>" (i.e.: "tox -e py314" or "tox -e lint")
#
# This tox configuration will skip any Python interpreters that can't be found.


[tox]
envlist =
    validate
    lint
    py310
    py314
skip_missing_interpreters = true


[testenv]
description = run tests
dependency_groups = test
commands =
    pytest {tty:--color=yes} {posargs:.}


[testenv:validate]
description = validate project configuration
dependency_groups = validate
commands =
    validate-pyproject pyproject.toml
    python -c "import treex"
    treex --help


[testenv:lint]
description = run linter and formatter
dependency_groups = lint
skip_install = true
commands =
    ruff check --fix --show-fixes --exit-non-zero-on-fix .
    ruff format --exit-non-zero-on-format .
